using Planeroo.Domain.Enums;

namespace Planeroo.Application.DTOs.Planning;

public record GeneratePlanningRequest(
    Guid ChildId,
    int WeekNumber,
    int Year,
    List<AvailabilitySlot>? AvailableSlots,
    bool AutoBalance = true,
    string Mode = "quick",
    string Source = "devoirs"  // "devoirs" | "timetable"
)
{
    // Allow callers to omit WeekNumber/Year — default to the current ISO week
    public static GeneratePlanningRequest ForCurrentWeek(Guid childId, List<AvailabilitySlot>? slots = null)
    {
        var now = DateTime.UtcNow;
        var week = System.Globalization.ISOWeek.GetWeekOfYear(now);
        var year = System.Globalization.ISOWeek.GetYear(now);
        return new GeneratePlanningRequest(childId, week, year, slots);
    }
};

public record AvailabilitySlot(
    DayOfWeekCustom DayOfWeek,
    TimeSpan StartTime,
    TimeSpan EndTime
);

public record PlanningSlotDto(
    Guid Id,
    Guid ChildId,
    Guid? HomeworkId,
    string DayOfWeek,
    string StartTime,
    string EndTime,
    string SlotType,
    string? Title,
    string? Subject,
    string? Notes,
    bool IsCompleted,
    bool IsAutoGenerated,
    int DurationMinutes,
    int Order
);

public record WeeklyPlanningDto(
    int WeekNumber,
    int Year,
    List<DayPlanDto> Days,
    int TotalStudyMinutes,
    int CompletedMinutes,
    double ProgressPercentage
);

public record DayPlanDto(
    string DayOfWeek,
    List<PlanningSlotDto> Slots,
    int TotalMinutes
);

public record MovePlanningSlotRequest(
    DayOfWeekCustom NewDayOfWeek,
    TimeSpan NewStartTime,
    TimeSpan NewEndTime,
    int NewOrder
);
