using Planeroo.Domain.Common;
using Planeroo.Domain.Enums;

namespace Planeroo.Domain.Entities;

/// <summary>
/// Individual planning slot within the weekly schedule.
/// </summary>
public class PlanningSlot : BaseEntity
{
    public Guid ChildId { get; set; }
    public Guid? HomeworkId { get; set; }
    public DayOfWeekCustom DayOfWeek { get; set; }
    public TimeSpan StartTime { get; set; }
    public TimeSpan EndTime { get; set; }
    public PlanningSlotType SlotType { get; set; } = PlanningSlotType.Study;
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public bool IsCompleted { get; set; } = false;
    public bool IsAutoGenerated { get; set; } = false;
    public int WeekNumber { get; set; }
    public int Year { get; set; }
    public int Order { get; set; }

    // Navigation
    public Child Child { get; set; } = null!;
    public Homework? Homework { get; set; }

    // Computed
    public int DurationMinutes => (int)(EndTime - StartTime).TotalMinutes;
}
